version: 2.1 

orbs:
  kubernetes: circleci/kubernetes@1.3.1
  
  
commands:
  start-minikube:
    steps:
      - run: docker pull rockymoyosu/pymod:latest
      - run: docker run rockymoyosu/pymod:latest
          
  test:
    steps:
      - run: 
          name: Running all unit tests 
          command: |
            echo "Success" 
 
jobs: 
  test: 
    parameters: 
        machine: 
          type: string 
          default: ubuntu-2004:202104-01 
    machine: 
      image: << parameters.machine >> 
 
    steps: 
      - checkout
      - start-minikube
      - kubernetes/install-kubectl
      - test
      
workflows: 
  version: 2 
  test-all-versions: 
    jobs: 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test
 
  all-node-versions: 
    jobs: 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test
 
  all-ruby-versions: 
    jobs: 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test
 